-- begin PIZZA_PIZZA
alter table PIZZA_PIZZA add constraint FK_PIZZA_PIZZA_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
create unique index IDX_PIZZA_PIZZA_UK_NAME on PIZZA_PIZZA (NAME) where DELETE_TS is null ^
create index IDX_PIZZA_PIZZA_ON_IMAGE on PIZZA_PIZZA (IMAGE_ID)^
-- end PIZZA_PIZZA
-- begin PIZZA_ORDER_POSITION
alter table PIZZA_ORDER_POSITION add constraint FK_PIZZA_ORDER_POSITION_ON_ORDER foreign key (ORDER_ID) references PIZZA_ORDER(ID)^
alter table PIZZA_ORDER_POSITION add constraint FK_PIZZA_ORDER_POSITION_ON_PIZZA foreign key (PIZZA_ID) references PIZZA_PIZZA(ID)^
create index IDX_PIZZA_ORDER_POSITION_ON_ORDER on PIZZA_ORDER_POSITION (ORDER_ID)^
create index IDX_PIZZA_ORDER_POSITION_ON_PIZZA on PIZZA_ORDER_POSITION (PIZZA_ID)^
-- end PIZZA_ORDER_POSITION
-- begin PIZZA_DELIVERY
alter table PIZZA_DELIVERY add constraint FK_PIZZA_DELIVERY_ON_DELIVERED_BY foreign key (DELIVERED_BY_ID) references SEC_USER(ID)^
alter table PIZZA_DELIVERY add constraint FK_PIZZA_DELIVERY_ON_ORDER foreign key (ORDER_ID) references PIZZA_ORDER(ID)^
create index IDX_PIZZA_DELIVERY_ON_DELIVERED_BY on PIZZA_DELIVERY (DELIVERED_BY_ID)^
create index IDX_PIZZA_DELIVERY_ON_ORDER on PIZZA_DELIVERY (ORDER_ID)^
-- end PIZZA_DELIVERY
-- begin PIZZA_ORDER
create unique index IDX_PIZZA_ORDER_UK_ORDER_NO on PIZZA_ORDER (ORDER_NO) where DELETE_TS is null ^
-- end PIZZA_ORDER
-- begin PIZZA_PIZZA_RECIPE
alter table PIZZA_PIZZA_RECIPE add constraint FK_PIZZA_RECIPE_ON_PIZZA foreign key (PIZZA_ID) references PIZZA_PIZZA(ID)^
alter table PIZZA_PIZZA_RECIPE add constraint FK_PIZZA_RECIPE_ON_INGREDIENT foreign key (INGREDIENT_ID) references PIZZA_INGREDIENT(ID)^
create index IDX_PIZZA_RECIPE_ON_PIZZA on PIZZA_PIZZA_RECIPE (PIZZA_ID)^
create index IDX_PIZZA_RECIPE_ON_INGREDIENT on PIZZA_PIZZA_RECIPE (INGREDIENT_ID)^
-- end PIZZA_PIZZA_RECIPE
-- begin PIZZA_PAYMENT
alter table PIZZA_PAYMENT add constraint FK_PIZZA_PAYMENT_ON_ORDER foreign key (ORDER_ID) references PIZZA_ORDER(ID)^
create index IDX_PIZZA_PAYMENT_ON_ORDER on PIZZA_PAYMENT (ORDER_ID)^
-- end PIZZA_PAYMENT
